---
abstract: 'Decodes, modifies and encodes TAP 3 files'
author:
  - 'Javier Gutierrez <jgutierrez@tap3edit.com>'
build_requires: {}
configure_requires: {}
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP3-Tap3edit
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Convert::ASN1: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.32
