name: TAP3-Tap3edit
version: 0.30
abstract: Decodes, modifies and encodes TAP3 files
author: Javier Gutierrez <jgutierrez at tap3edit dot com>
license: perl
distribution_type: module
requires:
  perl: 5.004
  Convert::ASN1: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
